// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/babit/nal/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAnalyticsStore creates a new instance of MockAnalyticsStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyticsStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyticsStore {
	mock := &MockAnalyticsStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnalyticsStore is an autogenerated mock type for the AnalyticsStore type
type MockAnalyticsStore struct {
	mock.Mock
}

type MockAnalyticsStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalyticsStore) EXPECT() *MockAnalyticsStore_Expecter {
	return &MockAnalyticsStore_Expecter{mock: &_m.Mock}
}

// Overview provides a mock function for the type MockAnalyticsStore
func (_mock *MockAnalyticsStore) Overview(ctx context.Context, days int32) (*ports.Overview, error) {
	ret := _mock.Called(ctx, days)

	if len(ret) == 0 {
		panic("no return value specified for Overview")
	}

	var r0 *ports.Overview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (*ports.Overview, error)); ok {
		return returnFunc(ctx, days)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) *ports.Overview); ok {
		r0 = returnFunc(ctx, days)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.Overview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, days)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsStore_Overview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Overview'
type MockAnalyticsStore_Overview_Call struct {
	*mock.Call
}

// Overview is a helper method to define mock.On call
//   - ctx context.Context
//   - days int32
func (_e *MockAnalyticsStore_Expecter) Overview(ctx any, days any) *MockAnalyticsStore_Overview_Call {
	return &MockAnalyticsStore_Overview_Call{Call: _e.mock.On("Overview", ctx, days)}
}

func (_c *MockAnalyticsStore_Overview_Call) Run(run func(ctx context.Context, days int32)) *MockAnalyticsStore_Overview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalyticsStore_Overview_Call) Return(overview *ports.Overview, err error) *MockAnalyticsStore_Overview_Call {
	_c.Call.Return(overview, err)
	return _c
}

func (_c *MockAnalyticsStore_Overview_Call) RunAndReturn(run func(ctx context.Context, days int32) (*ports.Overview, error)) *MockAnalyticsStore_Overview_Call {
	_c.Call.Return(run)
	return _c
}
