// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/babit/nal/gen/solari/ledger/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAnchor creates a new instance of MockAnchor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnchor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnchor {
	mock := &MockAnchor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnchor is an autogenerated mock type for the Anchor type
type MockAnchor struct {
	mock.Mock
}

type MockAnchor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnchor) EXPECT() *MockAnchor_Expecter {
	return &MockAnchor_Expecter{mock: &_m.Mock}
}

// Anchor provides a mock function for the type MockAnchor
func (_mock *MockAnchor) Anchor(ctx context.Context, sessionID string, root []byte) (*ledgerv1.Anchor, error) {
	ret := _mock.Called(ctx, sessionID, root)

	if len(ret) == 0 {
		panic("no return value specified for Anchor")
	}

	var r0 *ledgerv1.Anchor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (*ledgerv1.Anchor, error)); ok {
		return returnFunc(ctx, sessionID, root)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) *ledgerv1.Anchor); ok {
		r0 = returnFunc(ctx, sessionID, root)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ledgerv1.Anchor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, sessionID, root)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnchor_Anchor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Anchor'
type MockAnchor_Anchor_Call struct {
	*mock.Call
}

// Anchor is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - root []byte
func (_e *MockAnchor_Expecter) Anchor(ctx any, sessionID any, root any) *MockAnchor_Anchor_Call {
	return &MockAnchor_Anchor_Call{Call: _e.mock.On("Anchor", ctx, sessionID, root)}
}

func (_c *MockAnchor_Anchor_Call) Run(run func(ctx context.Context, sessionID string, root []byte)) *MockAnchor_Anchor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnchor_Anchor_Call) Return(anchor *ledgerv1.Anchor, err error) *MockAnchor_Anchor_Call {
	_c.Call.Return(anchor, err)
	return _c
}

func (_c *MockAnchor_Anchor_Call) RunAndReturn(run func(ctx context.Context, sessionID string, root []byte) (*ledgerv1.Anchor, error)) *MockAnchor_Anchor_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockAnchor
func (_mock *MockAnchor) Get(ctx context.Context, sessionID string) (*ledgerv1.Anchor, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *ledgerv1.Anchor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ledgerv1.Anchor, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ledgerv1.Anchor); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ledgerv1.Anchor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnchor_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAnchor_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockAnchor_Expecter) Get(ctx any, sessionID any) *MockAnchor_Get_Call {
	return &MockAnchor_Get_Call{Call: _e.mock.On("Get", ctx, sessionID)}
}

func (_c *MockAnchor_Get_Call) Run(run func(ctx context.Context, sessionID string)) *MockAnchor_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnchor_Get_Call) Return(anchor *ledgerv1.Anchor, err error) *MockAnchor_Get_Call {
	_c.Call.Return(anchor, err)
	return _c
}

func (_c *MockAnchor_Get_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*ledgerv1.Anchor, error)) *MockAnchor_Get_Call {
	_c.Call.Return(run)
	return _c
}
