// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/babit/nal/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAPIKeyStore creates a new instance of MockAPIKeyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyStore {
	mock := &MockAPIKeyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIKeyStore is an autogenerated mock type for the APIKeyStore type
type MockAPIKeyStore struct {
	mock.Mock
}

type MockAPIKeyStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyStore) EXPECT() *MockAPIKeyStore_Expecter {
	return &MockAPIKeyStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAPIKeyStore
func (_mock *MockAPIKeyStore) Create(ctx context.Context, in ports.APIKeyCreate) (*ports.APIKey, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *ports.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.APIKeyCreate) (*ports.APIKey, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.APIKeyCreate) *ports.APIKey); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.APIKeyCreate) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAPIKeyStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in ports.APIKeyCreate
func (_e *MockAPIKeyStore_Expecter) Create(ctx any, in any) *MockAPIKeyStore_Create_Call {
	return &MockAPIKeyStore_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockAPIKeyStore_Create_Call) Run(run func(ctx context.Context, in ports.APIKeyCreate)) *MockAPIKeyStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.APIKeyCreate
		if args[1] != nil {
			arg1 = args[1].(ports.APIKeyCreate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyStore_Create_Call) Return(aPIKey *ports.APIKey, err error) *MockAPIKeyStore_Create_Call {
	_c.Call.Return(aPIKey, err)
	return _c
}

func (_c *MockAPIKeyStore_Create_Call) RunAndReturn(run func(ctx context.Context, in ports.APIKeyCreate) (*ports.APIKey, error)) *MockAPIKeyStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function for the type MockAPIKeyStore
func (_mock *MockAPIKeyStore) GetByHash(ctx context.Context, keyHash string) (*ports.APIKey, error) {
	ret := _mock.Called(ctx, keyHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *ports.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ports.APIKey, error)); ok {
		return returnFunc(ctx, keyHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ports.APIKey); ok {
		r0 = returnFunc(ctx, keyHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, keyHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyStore_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockAPIKeyStore_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - keyHash string
func (_e *MockAPIKeyStore_Expecter) GetByHash(ctx any, keyHash any) *MockAPIKeyStore_GetByHash_Call {
	return &MockAPIKeyStore_GetByHash_Call{Call: _e.mock.On("GetByHash", ctx, keyHash)}
}

func (_c *MockAPIKeyStore_GetByHash_Call) Run(run func(ctx context.Context, keyHash string)) *MockAPIKeyStore_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyStore_GetByHash_Call) Return(aPIKey *ports.APIKey, err error) *MockAPIKeyStore_GetByHash_Call {
	_c.Call.Return(aPIKey, err)
	return _c
}

func (_c *MockAPIKeyStore_GetByHash_Call) RunAndReturn(run func(ctx context.Context, keyHash string) (*ports.APIKey, error)) *MockAPIKeyStore_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// ListByProject provides a mock function for the type MockAPIKeyStore
func (_mock *MockAPIKeyStore) ListByProject(ctx context.Context, projectID string) ([]*ports.APIKey, error) {
	ret := _mock.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ListByProject")
	}

	var r0 []*ports.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*ports.APIKey, error)); ok {
		return returnFunc(ctx, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*ports.APIKey); ok {
		r0 = returnFunc(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ports.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyStore_ListByProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByProject'
type MockAPIKeyStore_ListByProject_Call struct {
	*mock.Call
}

// ListByProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
func (_e *MockAPIKeyStore_Expecter) ListByProject(ctx any, projectID any) *MockAPIKeyStore_ListByProject_Call {
	return &MockAPIKeyStore_ListByProject_Call{Call: _e.mock.On("ListByProject", ctx, projectID)}
}

func (_c *MockAPIKeyStore_ListByProject_Call) Run(run func(ctx context.Context, projectID string)) *MockAPIKeyStore_ListByProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyStore_ListByProject_Call) Return(aPIKeys []*ports.APIKey, err error) *MockAPIKeyStore_ListByProject_Call {
	_c.Call.Return(aPIKeys, err)
	return _c
}

func (_c *MockAPIKeyStore_ListByProject_Call) RunAndReturn(run func(ctx context.Context, projectID string) ([]*ports.APIKey, error)) *MockAPIKeyStore_ListByProject_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockAPIKeyStore
func (_mock *MockAPIKeyStore) Revoke(ctx context.Context, id string, userID string) (bool, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyStore_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockAPIKeyStore_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockAPIKeyStore_Expecter) Revoke(ctx any, id any, userID any) *MockAPIKeyStore_Revoke_Call {
	return &MockAPIKeyStore_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id, userID)}
}

func (_c *MockAPIKeyStore_Revoke_Call) Run(run func(ctx context.Context, id string, userID string)) *MockAPIKeyStore_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPIKeyStore_Revoke_Call) Return(b bool, err error) *MockAPIKeyStore_Revoke_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAPIKeyStore_Revoke_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) (bool, error)) *MockAPIKeyStore_Revoke_Call {
	_c.Call.Return(run)
	return _c
}
