// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/babit/nal/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBrandResolver creates a new instance of MockBrandResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrandResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrandResolver {
	mock := &MockBrandResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrandResolver is an autogenerated mock type for the BrandResolver type
type MockBrandResolver struct {
	mock.Mock
}

type MockBrandResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrandResolver) EXPECT() *MockBrandResolver_Expecter {
	return &MockBrandResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockBrandResolver
func (_mock *MockBrandResolver) Resolve(ctx context.Context, domain string) (ports.Branding, error) {
	ret := _mock.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 ports.Branding
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ports.Branding, error)); ok {
		return returnFunc(ctx, domain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ports.Branding); ok {
		r0 = returnFunc(ctx, domain)
	} else {
		r0 = ret.Get(0).(ports.Branding)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBrandResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockBrandResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockBrandResolver_Expecter) Resolve(ctx any, domain any) *MockBrandResolver_Resolve_Call {
	return &MockBrandResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx, domain)}
}

func (_c *MockBrandResolver_Resolve_Call) Run(run func(ctx context.Context, domain string)) *MockBrandResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrandResolver_Resolve_Call) Return(branding ports.Branding, err error) *MockBrandResolver_Resolve_Call {
	_c.Call.Return(branding, err)
	return _c
}

func (_c *MockBrandResolver_Resolve_Call) RunAndReturn(run func(ctx context.Context, domain string) (ports.Branding, error)) *MockBrandResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
