// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/babit/nal/gen/solari/ledger/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCheckpointer creates a new instance of MockCheckpointer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckpointer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckpointer {
	mock := &MockCheckpointer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCheckpointer is an autogenerated mock type for the Checkpointer type
type MockCheckpointer struct {
	mock.Mock
}

type MockCheckpointer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckpointer) EXPECT() *MockCheckpointer_Expecter {
	return &MockCheckpointer_Expecter{mock: &_m.Mock}
}

// Checkpoint provides a mock function for the type MockCheckpointer
func (_mock *MockCheckpointer) Checkpoint(ctx context.Context, sessionID string) (*ledgerv1.Anchor, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Checkpoint")
	}

	var r0 *ledgerv1.Anchor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ledgerv1.Anchor, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ledgerv1.Anchor); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ledgerv1.Anchor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCheckpointer_Checkpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkpoint'
type MockCheckpointer_Checkpoint_Call struct {
	*mock.Call
}

// Checkpoint is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockCheckpointer_Expecter) Checkpoint(ctx any, sessionID any) *MockCheckpointer_Checkpoint_Call {
	return &MockCheckpointer_Checkpoint_Call{Call: _e.mock.On("Checkpoint", ctx, sessionID)}
}

func (_c *MockCheckpointer_Checkpoint_Call) Run(run func(ctx context.Context, sessionID string)) *MockCheckpointer_Checkpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCheckpointer_Checkpoint_Call) Return(anchor *ledgerv1.Anchor, err error) *MockCheckpointer_Checkpoint_Call {
	_c.Call.Return(anchor, err)
	return _c
}

func (_c *MockCheckpointer_Checkpoint_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*ledgerv1.Anchor, error)) *MockCheckpointer_Checkpoint_Call {
	_c.Call.Return(run)
	return _c
}
