// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/babit/nal/gen/solari/ledger/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDelegationVerifier creates a new instance of MockDelegationVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDelegationVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDelegationVerifier {
	mock := &MockDelegationVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDelegationVerifier is an autogenerated mock type for the DelegationVerifier type
type MockDelegationVerifier struct {
	mock.Mock
}

type MockDelegationVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDelegationVerifier) EXPECT() *MockDelegationVerifier_Expecter {
	return &MockDelegationVerifier_Expecter{mock: &_m.Mock}
}

// Authorizes provides a mock function for the type MockDelegationVerifier
func (_mock *MockDelegationVerifier) Authorizes(grant *ledgerv1.Grant, capability string, resource string, valueCents int64) error {
	ret := _mock.Called(grant, capability, resource, valueCents)

	if len(ret) == 0 {
		panic("no return value specified for Authorizes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*ledgerv1.Grant, string, string, int64) error); ok {
		r0 = returnFunc(grant, capability, resource, valueCents)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDelegationVerifier_Authorizes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorizes'
type MockDelegationVerifier_Authorizes_Call struct {
	*mock.Call
}

// Authorizes is a helper method to define mock.On call
//   - grant *ledgerv1.Grant
//   - capability string
//   - resource string
//   - valueCents int64
func (_e *MockDelegationVerifier_Expecter) Authorizes(grant any, capability any, resource any, valueCents any) *MockDelegationVerifier_Authorizes_Call {
	return &MockDelegationVerifier_Authorizes_Call{Call: _e.mock.On("Authorizes", grant, capability, resource, valueCents)}
}

func (_c *MockDelegationVerifier_Authorizes_Call) Run(run func(grant *ledgerv1.Grant, capability string, resource string, valueCents int64)) *MockDelegationVerifier_Authorizes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ledgerv1.Grant
		if args[0] != nil {
			arg0 = args[0].(*ledgerv1.Grant)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDelegationVerifier_Authorizes_Call) Return(err error) *MockDelegationVerifier_Authorizes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDelegationVerifier_Authorizes_Call) RunAndReturn(run func(grant *ledgerv1.Grant, capability string, resource string, valueCents int64) error) *MockDelegationVerifier_Authorizes_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyChain provides a mock function for the type MockDelegationVerifier
func (_mock *MockDelegationVerifier) VerifyChain(chain []*ledgerv1.Grant, now time.Time) error {
	ret := _mock.Called(chain, now)

	if len(ret) == 0 {
		panic("no return value specified for VerifyChain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*ledgerv1.Grant, time.Time) error); ok {
		r0 = returnFunc(chain, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDelegationVerifier_VerifyChain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyChain'
type MockDelegationVerifier_VerifyChain_Call struct {
	*mock.Call
}

// VerifyChain is a helper method to define mock.On call
//   - chain []*ledgerv1.Grant
//   - now time.Time
func (_e *MockDelegationVerifier_Expecter) VerifyChain(chain any, now any) *MockDelegationVerifier_VerifyChain_Call {
	return &MockDelegationVerifier_VerifyChain_Call{Call: _e.mock.On("VerifyChain", chain, now)}
}

func (_c *MockDelegationVerifier_VerifyChain_Call) Run(run func(chain []*ledgerv1.Grant, now time.Time)) *MockDelegationVerifier_VerifyChain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*ledgerv1.Grant
		if args[0] != nil {
			arg0 = args[0].([]*ledgerv1.Grant)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDelegationVerifier_VerifyChain_Call) Return(err error) *MockDelegationVerifier_VerifyChain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDelegationVerifier_VerifyChain_Call) RunAndReturn(run func(chain []*ledgerv1.Grant, now time.Time) error) *MockDelegationVerifier_VerifyChain_Call {
	_c.Call.Return(run)
	return _c
}
