// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/babit/nal/gen/solari/ledger/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventStore creates a new instance of MockEventStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventStore {
	mock := &MockEventStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventStore is an autogenerated mock type for the EventStore type
type MockEventStore struct {
	mock.Mock
}

type MockEventStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventStore) EXPECT() *MockEventStore_Expecter {
	return &MockEventStore_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type MockEventStore
func (_mock *MockEventStore) Append(ctx context.Context, event *ledgerv1.ActionEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ledgerv1.ActionEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventStore_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockEventStore_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - event *ledgerv1.ActionEvent
func (_e *MockEventStore_Expecter) Append(ctx any, event any) *MockEventStore_Append_Call {
	return &MockEventStore_Append_Call{Call: _e.mock.On("Append", ctx, event)}
}

func (_c *MockEventStore_Append_Call) Run(run func(ctx context.Context, event *ledgerv1.ActionEvent)) *MockEventStore_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ledgerv1.ActionEvent
		if args[1] != nil {
			arg1 = args[1].(*ledgerv1.ActionEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventStore_Append_Call) Return(err error) *MockEventStore_Append_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventStore_Append_Call) RunAndReturn(run func(ctx context.Context, event *ledgerv1.ActionEvent) error) *MockEventStore_Append_Call {
	_c.Call.Return(run)
	return _c
}

// BySession provides a mock function for the type MockEventStore
func (_mock *MockEventStore) BySession(ctx context.Context, sessionID string) ([]*ledgerv1.ActionEvent, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for BySession")
	}

	var r0 []*ledgerv1.ActionEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*ledgerv1.ActionEvent, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*ledgerv1.ActionEvent); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ledgerv1.ActionEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventStore_BySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BySession'
type MockEventStore_BySession_Call struct {
	*mock.Call
}

// BySession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockEventStore_Expecter) BySession(ctx any, sessionID any) *MockEventStore_BySession_Call {
	return &MockEventStore_BySession_Call{Call: _e.mock.On("BySession", ctx, sessionID)}
}

func (_c *MockEventStore_BySession_Call) Run(run func(ctx context.Context, sessionID string)) *MockEventStore_BySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventStore_BySession_Call) Return(actionEvents []*ledgerv1.ActionEvent, err error) *MockEventStore_BySession_Call {
	_c.Call.Return(actionEvents, err)
	return _c
}

func (_c *MockEventStore_BySession_Call) RunAndReturn(run func(ctx context.Context, sessionID string) ([]*ledgerv1.ActionEvent, error)) *MockEventStore_BySession_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockEventStore
func (_mock *MockEventStore) Get(ctx context.Context, eventID string) (*ledgerv1.ActionEvent, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *ledgerv1.ActionEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ledgerv1.ActionEvent, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ledgerv1.ActionEvent); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ledgerv1.ActionEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockEventStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
func (_e *MockEventStore_Expecter) Get(ctx any, eventID any) *MockEventStore_Get_Call {
	return &MockEventStore_Get_Call{Call: _e.mock.On("Get", ctx, eventID)}
}

func (_c *MockEventStore_Get_Call) Run(run func(ctx context.Context, eventID string)) *MockEventStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventStore_Get_Call) Return(actionEvent *ledgerv1.ActionEvent, err error) *MockEventStore_Get_Call {
	_c.Call.Return(actionEvent, err)
	return _c
}

func (_c *MockEventStore_Get_Call) RunAndReturn(run func(ctx context.Context, eventID string) (*ledgerv1.ActionEvent, error)) *MockEventStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Last provides a mock function for the type MockEventStore
func (_mock *MockEventStore) Last(ctx context.Context, sessionID string) (*ledgerv1.ActionEvent, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Last")
	}

	var r0 *ledgerv1.ActionEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ledgerv1.ActionEvent, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ledgerv1.ActionEvent); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ledgerv1.ActionEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventStore_Last_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Last'
type MockEventStore_Last_Call struct {
	*mock.Call
}

// Last is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockEventStore_Expecter) Last(ctx any, sessionID any) *MockEventStore_Last_Call {
	return &MockEventStore_Last_Call{Call: _e.mock.On("Last", ctx, sessionID)}
}

func (_c *MockEventStore_Last_Call) Run(run func(ctx context.Context, sessionID string)) *MockEventStore_Last_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventStore_Last_Call) Return(actionEvent *ledgerv1.ActionEvent, err error) *MockEventStore_Last_Call {
	_c.Call.Return(actionEvent, err)
	return _c
}

func (_c *MockEventStore_Last_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*ledgerv1.ActionEvent, error)) *MockEventStore_Last_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockEventStore
func (_mock *MockEventStore) List(ctx context.Context, projectID string, pageSize int32, pageToken string) ([]*ledgerv1.ActionEvent, string, error) {
	ret := _mock.Called(ctx, projectID, pageSize, pageToken)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*ledgerv1.ActionEvent
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int32, string) ([]*ledgerv1.ActionEvent, string, error)); ok {
		return returnFunc(ctx, projectID, pageSize, pageToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int32, string) []*ledgerv1.ActionEvent); ok {
		r0 = returnFunc(ctx, projectID, pageSize, pageToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ledgerv1.ActionEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int32, string) string); ok {
		r1 = returnFunc(ctx, projectID, pageSize, pageToken)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int32, string) error); ok {
		r2 = returnFunc(ctx, projectID, pageSize, pageToken)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockEventStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockEventStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - pageSize int32
//   - pageToken string
func (_e *MockEventStore_Expecter) List(ctx any, projectID any, pageSize any, pageToken any) *MockEventStore_List_Call {
	return &MockEventStore_List_Call{Call: _e.mock.On("List", ctx, projectID, pageSize, pageToken)}
}

func (_c *MockEventStore_List_Call) Run(run func(ctx context.Context, projectID string, pageSize int32, pageToken string)) *MockEventStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEventStore_List_Call) Return(actionEvents []*ledgerv1.ActionEvent, s string, err error) *MockEventStore_List_Call {
	_c.Call.Return(actionEvents, s, err)
	return _c
}

func (_c *MockEventStore_List_Call) RunAndReturn(run func(ctx context.Context, projectID string, pageSize int32, pageToken string) ([]*ledgerv1.ActionEvent, string, error)) *MockEventStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Range provides a mock function for the type MockEventStore
func (_mock *MockEventStore) Range(ctx context.Context, fromSeq int64, toSeq int64) ([]*ledgerv1.ActionEvent, error) {
	ret := _mock.Called(ctx, fromSeq, toSeq)

	if len(ret) == 0 {
		panic("no return value specified for Range")
	}

	var r0 []*ledgerv1.ActionEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) ([]*ledgerv1.ActionEvent, error)); ok {
		return returnFunc(ctx, fromSeq, toSeq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) []*ledgerv1.ActionEvent); ok {
		r0 = returnFunc(ctx, fromSeq, toSeq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ledgerv1.ActionEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, fromSeq, toSeq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventStore_Range_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Range'
type MockEventStore_Range_Call struct {
	*mock.Call
}

// Range is a helper method to define mock.On call
//   - ctx context.Context
//   - fromSeq int64
//   - toSeq int64
func (_e *MockEventStore_Expecter) Range(ctx any, fromSeq any, toSeq any) *MockEventStore_Range_Call {
	return &MockEventStore_Range_Call{Call: _e.mock.On("Range", ctx, fromSeq, toSeq)}
}

func (_c *MockEventStore_Range_Call) Run(run func(ctx context.Context, fromSeq int64, toSeq int64)) *MockEventStore_Range_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventStore_Range_Call) Return(actionEvents []*ledgerv1.ActionEvent, err error) *MockEventStore_Range_Call {
	_c.Call.Return(actionEvents, err)
	return _c
}

func (_c *MockEventStore_Range_Call) RunAndReturn(run func(ctx context.Context, fromSeq int64, toSeq int64) ([]*ledgerv1.ActionEvent, error)) *MockEventStore_Range_Call {
	_c.Call.Return(run)
	return _c
}
