// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/babit/nal/gen/solari/ledger/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGrantStore creates a new instance of MockGrantStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGrantStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGrantStore {
	mock := &MockGrantStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGrantStore is an autogenerated mock type for the GrantStore type
type MockGrantStore struct {
	mock.Mock
}

type MockGrantStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGrantStore) EXPECT() *MockGrantStore_Expecter {
	return &MockGrantStore_Expecter{mock: &_m.Mock}
}

// Chain provides a mock function for the type MockGrantStore
func (_mock *MockGrantStore) Chain(ctx context.Context, grantID string) ([]*ledgerv1.Grant, error) {
	ret := _mock.Called(ctx, grantID)

	if len(ret) == 0 {
		panic("no return value specified for Chain")
	}

	var r0 []*ledgerv1.Grant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*ledgerv1.Grant, error)); ok {
		return returnFunc(ctx, grantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*ledgerv1.Grant); ok {
		r0 = returnFunc(ctx, grantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ledgerv1.Grant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, grantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantStore_Chain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chain'
type MockGrantStore_Chain_Call struct {
	*mock.Call
}

// Chain is a helper method to define mock.On call
//   - ctx context.Context
//   - grantID string
func (_e *MockGrantStore_Expecter) Chain(ctx any, grantID any) *MockGrantStore_Chain_Call {
	return &MockGrantStore_Chain_Call{Call: _e.mock.On("Chain", ctx, grantID)}
}

func (_c *MockGrantStore_Chain_Call) Run(run func(ctx context.Context, grantID string)) *MockGrantStore_Chain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrantStore_Chain_Call) Return(grants []*ledgerv1.Grant, err error) *MockGrantStore_Chain_Call {
	_c.Call.Return(grants, err)
	return _c
}

func (_c *MockGrantStore_Chain_Call) RunAndReturn(run func(ctx context.Context, grantID string) ([]*ledgerv1.Grant, error)) *MockGrantStore_Chain_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockGrantStore
func (_mock *MockGrantStore) Get(ctx context.Context, grantID string) (*ledgerv1.Grant, error) {
	ret := _mock.Called(ctx, grantID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *ledgerv1.Grant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ledgerv1.Grant, error)); ok {
		return returnFunc(ctx, grantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ledgerv1.Grant); ok {
		r0 = returnFunc(ctx, grantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ledgerv1.Grant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, grantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockGrantStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - grantID string
func (_e *MockGrantStore_Expecter) Get(ctx any, grantID any) *MockGrantStore_Get_Call {
	return &MockGrantStore_Get_Call{Call: _e.mock.On("Get", ctx, grantID)}
}

func (_c *MockGrantStore_Get_Call) Run(run func(ctx context.Context, grantID string)) *MockGrantStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrantStore_Get_Call) Return(grant *ledgerv1.Grant, err error) *MockGrantStore_Get_Call {
	_c.Call.Return(grant, err)
	return _c
}

func (_c *MockGrantStore_Get_Call) RunAndReturn(run func(ctx context.Context, grantID string) (*ledgerv1.Grant, error)) *MockGrantStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// IsRevoked provides a mock function for the type MockGrantStore
func (_mock *MockGrantStore) IsRevoked(ctx context.Context, grantID string) (bool, error) {
	ret := _mock.Called(ctx, grantID)

	if len(ret) == 0 {
		panic("no return value specified for IsRevoked")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, grantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, grantID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, grantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrantStore_IsRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRevoked'
type MockGrantStore_IsRevoked_Call struct {
	*mock.Call
}

// IsRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - grantID string
func (_e *MockGrantStore_Expecter) IsRevoked(ctx any, grantID any) *MockGrantStore_IsRevoked_Call {
	return &MockGrantStore_IsRevoked_Call{Call: _e.mock.On("IsRevoked", ctx, grantID)}
}

func (_c *MockGrantStore_IsRevoked_Call) Run(run func(ctx context.Context, grantID string)) *MockGrantStore_IsRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrantStore_IsRevoked_Call) Return(b bool, err error) *MockGrantStore_IsRevoked_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGrantStore_IsRevoked_Call) RunAndReturn(run func(ctx context.Context, grantID string) (bool, error)) *MockGrantStore_IsRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockGrantStore
func (_mock *MockGrantStore) List(ctx context.Context, projectID string, pageSize int32, pageToken string) ([]*ledgerv1.Grant, string, error) {
	ret := _mock.Called(ctx, projectID, pageSize, pageToken)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*ledgerv1.Grant
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int32, string) ([]*ledgerv1.Grant, string, error)); ok {
		return returnFunc(ctx, projectID, pageSize, pageToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int32, string) []*ledgerv1.Grant); ok {
		r0 = returnFunc(ctx, projectID, pageSize, pageToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ledgerv1.Grant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int32, string) string); ok {
		r1 = returnFunc(ctx, projectID, pageSize, pageToken)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int32, string) error); ok {
		r2 = returnFunc(ctx, projectID, pageSize, pageToken)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGrantStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockGrantStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - pageSize int32
//   - pageToken string
func (_e *MockGrantStore_Expecter) List(ctx any, projectID any, pageSize any, pageToken any) *MockGrantStore_List_Call {
	return &MockGrantStore_List_Call{Call: _e.mock.On("List", ctx, projectID, pageSize, pageToken)}
}

func (_c *MockGrantStore_List_Call) Run(run func(ctx context.Context, projectID string, pageSize int32, pageToken string)) *MockGrantStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGrantStore_List_Call) Return(grants []*ledgerv1.Grant, s string, err error) *MockGrantStore_List_Call {
	_c.Call.Return(grants, s, err)
	return _c
}

func (_c *MockGrantStore_List_Call) RunAndReturn(run func(ctx context.Context, projectID string, pageSize int32, pageToken string) ([]*ledgerv1.Grant, string, error)) *MockGrantStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockGrantStore
func (_mock *MockGrantStore) Put(ctx context.Context, grant *ledgerv1.Grant) error {
	ret := _mock.Called(ctx, grant)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ledgerv1.Grant) error); ok {
		r0 = returnFunc(ctx, grant)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrantStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockGrantStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - grant *ledgerv1.Grant
func (_e *MockGrantStore_Expecter) Put(ctx any, grant any) *MockGrantStore_Put_Call {
	return &MockGrantStore_Put_Call{Call: _e.mock.On("Put", ctx, grant)}
}

func (_c *MockGrantStore_Put_Call) Run(run func(ctx context.Context, grant *ledgerv1.Grant)) *MockGrantStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ledgerv1.Grant
		if args[1] != nil {
			arg1 = args[1].(*ledgerv1.Grant)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrantStore_Put_Call) Return(err error) *MockGrantStore_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrantStore_Put_Call) RunAndReturn(run func(ctx context.Context, grant *ledgerv1.Grant) error) *MockGrantStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockGrantStore
func (_mock *MockGrantStore) Revoke(ctx context.Context, grantID string, reason string) error {
	ret := _mock.Called(ctx, grantID, reason)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, grantID, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGrantStore_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockGrantStore_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - grantID string
//   - reason string
func (_e *MockGrantStore_Expecter) Revoke(ctx any, grantID any, reason any) *MockGrantStore_Revoke_Call {
	return &MockGrantStore_Revoke_Call{Call: _e.mock.On("Revoke", ctx, grantID, reason)}
}

func (_c *MockGrantStore_Revoke_Call) Run(run func(ctx context.Context, grantID string, reason string)) *MockGrantStore_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGrantStore_Revoke_Call) Return(err error) *MockGrantStore_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGrantStore_Revoke_Call) RunAndReturn(run func(ctx context.Context, grantID string, reason string) error) *MockGrantStore_Revoke_Call {
	_c.Call.Return(run)
	return _c
}
