// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIDGen creates a new instance of MockIDGen. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDGen(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDGen {
	mock := &MockIDGen{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIDGen is an autogenerated mock type for the IDGen type
type MockIDGen struct {
	mock.Mock
}

type MockIDGen_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDGen) EXPECT() *MockIDGen_Expecter {
	return &MockIDGen_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockIDGen
func (_mock *MockIDGen) New(prefix string) string {
	ret := _mock.Called(prefix)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(prefix)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIDGen_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockIDGen_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - prefix string
func (_e *MockIDGen_Expecter) New(prefix any) *MockIDGen_New_Call {
	return &MockIDGen_New_Call{Call: _e.mock.On("New", prefix)}
}

func (_c *MockIDGen_New_Call) Run(run func(prefix string)) *MockIDGen_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDGen_New_Call) Return(s string) *MockIDGen_New_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIDGen_New_Call) RunAndReturn(run func(prefix string) string) *MockIDGen_New_Call {
	_c.Call.Return(run)
	return _c
}
