// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMerkleTree creates a new instance of MockMerkleTree. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMerkleTree(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMerkleTree {
	mock := &MockMerkleTree{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMerkleTree is an autogenerated mock type for the MerkleTree type
type MockMerkleTree struct {
	mock.Mock
}

type MockMerkleTree_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMerkleTree) EXPECT() *MockMerkleTree_Expecter {
	return &MockMerkleTree_Expecter{mock: &_m.Mock}
}

// Path provides a mock function for the type MockMerkleTree
func (_mock *MockMerkleTree) Path(leaves [][]byte, index int) ([][]byte, error) {
	ret := _mock.Called(leaves, index)

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 [][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([][]byte, int) ([][]byte, error)); ok {
		return returnFunc(leaves, index)
	}
	if returnFunc, ok := ret.Get(0).(func([][]byte, int) [][]byte); ok {
		r0 = returnFunc(leaves, index)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([][]byte, int) error); ok {
		r1 = returnFunc(leaves, index)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMerkleTree_Path_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Path'
type MockMerkleTree_Path_Call struct {
	*mock.Call
}

// Path is a helper method to define mock.On call
//   - leaves [][]byte
//   - index int
func (_e *MockMerkleTree_Expecter) Path(leaves any, index any) *MockMerkleTree_Path_Call {
	return &MockMerkleTree_Path_Call{Call: _e.mock.On("Path", leaves, index)}
}

func (_c *MockMerkleTree_Path_Call) Run(run func(leaves [][]byte, index int)) *MockMerkleTree_Path_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 [][]byte
		if args[0] != nil {
			arg0 = args[0].([][]byte)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMerkleTree_Path_Call) Return(bytess [][]byte, err error) *MockMerkleTree_Path_Call {
	_c.Call.Return(bytess, err)
	return _c
}

func (_c *MockMerkleTree_Path_Call) RunAndReturn(run func(leaves [][]byte, index int) ([][]byte, error)) *MockMerkleTree_Path_Call {
	_c.Call.Return(run)
	return _c
}

// Root provides a mock function for the type MockMerkleTree
func (_mock *MockMerkleTree) Root(leaves [][]byte) []byte {
	ret := _mock.Called(leaves)

	if len(ret) == 0 {
		panic("no return value specified for Root")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func([][]byte) []byte); ok {
		r0 = returnFunc(leaves)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockMerkleTree_Root_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Root'
type MockMerkleTree_Root_Call struct {
	*mock.Call
}

// Root is a helper method to define mock.On call
//   - leaves [][]byte
func (_e *MockMerkleTree_Expecter) Root(leaves any) *MockMerkleTree_Root_Call {
	return &MockMerkleTree_Root_Call{Call: _e.mock.On("Root", leaves)}
}

func (_c *MockMerkleTree_Root_Call) Run(run func(leaves [][]byte)) *MockMerkleTree_Root_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 [][]byte
		if args[0] != nil {
			arg0 = args[0].([][]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMerkleTree_Root_Call) Return(bytes []byte) *MockMerkleTree_Root_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockMerkleTree_Root_Call) RunAndReturn(run func(leaves [][]byte) []byte) *MockMerkleTree_Root_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockMerkleTree
func (_mock *MockMerkleTree) Verify(leaf []byte, path [][]byte, root []byte, index int) bool {
	ret := _mock.Called(leaf, path, root, index)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func([]byte, [][]byte, []byte, int) bool); ok {
		r0 = returnFunc(leaf, path, root, index)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockMerkleTree_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockMerkleTree_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - leaf []byte
//   - path [][]byte
//   - root []byte
//   - index int
func (_e *MockMerkleTree_Expecter) Verify(leaf any, path any, root any, index any) *MockMerkleTree_Verify_Call {
	return &MockMerkleTree_Verify_Call{Call: _e.mock.On("Verify", leaf, path, root, index)}
}

func (_c *MockMerkleTree_Verify_Call) Run(run func(leaf []byte, path [][]byte, root []byte, index int)) *MockMerkleTree_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 [][]byte
		if args[1] != nil {
			arg1 = args[1].([][]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMerkleTree_Verify_Call) Return(b bool) *MockMerkleTree_Verify_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockMerkleTree_Verify_Call) RunAndReturn(run func(leaf []byte, path [][]byte, root []byte, index int) bool) *MockMerkleTree_Verify_Call {
	_c.Call.Return(run)
	return _c
}
