// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/babit/nal/gen/solari/ledger/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotarizer creates a new instance of MockNotarizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotarizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotarizer {
	mock := &MockNotarizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotarizer is an autogenerated mock type for the Notarizer type
type MockNotarizer struct {
	mock.Mock
}

type MockNotarizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotarizer) EXPECT() *MockNotarizer_Expecter {
	return &MockNotarizer_Expecter{mock: &_m.Mock}
}

// Notarize provides a mock function for the type MockNotarizer
func (_mock *MockNotarizer) Notarize(ctx context.Context, draft *ledgerv1.ActionEvent) (*ledgerv1.ActionEvent, error) {
	ret := _mock.Called(ctx, draft)

	if len(ret) == 0 {
		panic("no return value specified for Notarize")
	}

	var r0 *ledgerv1.ActionEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ledgerv1.ActionEvent) (*ledgerv1.ActionEvent, error)); ok {
		return returnFunc(ctx, draft)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ledgerv1.ActionEvent) *ledgerv1.ActionEvent); ok {
		r0 = returnFunc(ctx, draft)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ledgerv1.ActionEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ledgerv1.ActionEvent) error); ok {
		r1 = returnFunc(ctx, draft)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotarizer_Notarize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notarize'
type MockNotarizer_Notarize_Call struct {
	*mock.Call
}

// Notarize is a helper method to define mock.On call
//   - ctx context.Context
//   - draft *ledgerv1.ActionEvent
func (_e *MockNotarizer_Expecter) Notarize(ctx any, draft any) *MockNotarizer_Notarize_Call {
	return &MockNotarizer_Notarize_Call{Call: _e.mock.On("Notarize", ctx, draft)}
}

func (_c *MockNotarizer_Notarize_Call) Run(run func(ctx context.Context, draft *ledgerv1.ActionEvent)) *MockNotarizer_Notarize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ledgerv1.ActionEvent
		if args[1] != nil {
			arg1 = args[1].(*ledgerv1.ActionEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotarizer_Notarize_Call) Return(actionEvent *ledgerv1.ActionEvent, err error) *MockNotarizer_Notarize_Call {
	_c.Call.Return(actionEvent, err)
	return _c
}

func (_c *MockNotarizer_Notarize_Call) RunAndReturn(run func(ctx context.Context, draft *ledgerv1.ActionEvent) (*ledgerv1.ActionEvent, error)) *MockNotarizer_Notarize_Call {
	_c.Call.Return(run)
	return _c
}
