// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/babit/nal/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProjectStore creates a new instance of MockProjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectStore {
	mock := &MockProjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectStore is an autogenerated mock type for the ProjectStore type
type MockProjectStore struct {
	mock.Mock
}

type MockProjectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectStore) EXPECT() *MockProjectStore_Expecter {
	return &MockProjectStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockProjectStore
func (_mock *MockProjectStore) Create(ctx context.Context, userID string, name string) (*ports.Project, error) {
	ret := _mock.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *ports.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*ports.Project, error)); ok {
		return returnFunc(ctx, userID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *ports.Project); ok {
		r0 = returnFunc(ctx, userID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProjectStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - name string
func (_e *MockProjectStore_Expecter) Create(ctx any, userID any, name any) *MockProjectStore_Create_Call {
	return &MockProjectStore_Create_Call{Call: _e.mock.On("Create", ctx, userID, name)}
}

func (_c *MockProjectStore_Create_Call) Run(run func(ctx context.Context, userID string, name string)) *MockProjectStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProjectStore_Create_Call) Return(project *ports.Project, err error) *MockProjectStore_Create_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockProjectStore_Create_Call) RunAndReturn(run func(ctx context.Context, userID string, name string) (*ports.Project, error)) *MockProjectStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetForUser provides a mock function for the type MockProjectStore
func (_mock *MockProjectStore) GetForUser(ctx context.Context, id string, userID string) (*ports.Project, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetForUser")
	}

	var r0 *ports.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*ports.Project, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *ports.Project); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectStore_GetForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForUser'
type MockProjectStore_GetForUser_Call struct {
	*mock.Call
}

// GetForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockProjectStore_Expecter) GetForUser(ctx any, id any, userID any) *MockProjectStore_GetForUser_Call {
	return &MockProjectStore_GetForUser_Call{Call: _e.mock.On("GetForUser", ctx, id, userID)}
}

func (_c *MockProjectStore_GetForUser_Call) Run(run func(ctx context.Context, id string, userID string)) *MockProjectStore_GetForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProjectStore_GetForUser_Call) Return(project *ports.Project, err error) *MockProjectStore_GetForUser_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockProjectStore_GetForUser_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) (*ports.Project, error)) *MockProjectStore_GetForUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockProjectStore
func (_mock *MockProjectStore) ListByUser(ctx context.Context, userID string) ([]*ports.Project, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*ports.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*ports.Project, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*ports.Project); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ports.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectStore_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockProjectStore_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockProjectStore_Expecter) ListByUser(ctx any, userID any) *MockProjectStore_ListByUser_Call {
	return &MockProjectStore_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockProjectStore_ListByUser_Call) Run(run func(ctx context.Context, userID string)) *MockProjectStore_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectStore_ListByUser_Call) Return(projects []*ports.Project, err error) *MockProjectStore_ListByUser_Call {
	_c.Call.Return(projects, err)
	return _c
}

func (_c *MockProjectStore_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*ports.Project, error)) *MockProjectStore_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}
