// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/babit/nal/gen/solari/ledger/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSealer creates a new instance of MockSealer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSealer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSealer {
	mock := &MockSealer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSealer is an autogenerated mock type for the Sealer type
type MockSealer struct {
	mock.Mock
}

type MockSealer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSealer) EXPECT() *MockSealer_Expecter {
	return &MockSealer_Expecter{mock: &_m.Mock}
}

// Seal provides a mock function for the type MockSealer
func (_mock *MockSealer) Seal(event *ledgerv1.ActionEvent, prev *ledgerv1.ActionEvent) (*ledgerv1.ActionEvent, error) {
	ret := _mock.Called(event, prev)

	if len(ret) == 0 {
		panic("no return value specified for Seal")
	}

	var r0 *ledgerv1.ActionEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*ledgerv1.ActionEvent, *ledgerv1.ActionEvent) (*ledgerv1.ActionEvent, error)); ok {
		return returnFunc(event, prev)
	}
	if returnFunc, ok := ret.Get(0).(func(*ledgerv1.ActionEvent, *ledgerv1.ActionEvent) *ledgerv1.ActionEvent); ok {
		r0 = returnFunc(event, prev)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ledgerv1.ActionEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*ledgerv1.ActionEvent, *ledgerv1.ActionEvent) error); ok {
		r1 = returnFunc(event, prev)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSealer_Seal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seal'
type MockSealer_Seal_Call struct {
	*mock.Call
}

// Seal is a helper method to define mock.On call
//   - event *ledgerv1.ActionEvent
//   - prev *ledgerv1.ActionEvent
func (_e *MockSealer_Expecter) Seal(event any, prev any) *MockSealer_Seal_Call {
	return &MockSealer_Seal_Call{Call: _e.mock.On("Seal", event, prev)}
}

func (_c *MockSealer_Seal_Call) Run(run func(event *ledgerv1.ActionEvent, prev *ledgerv1.ActionEvent)) *MockSealer_Seal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ledgerv1.ActionEvent
		if args[0] != nil {
			arg0 = args[0].(*ledgerv1.ActionEvent)
		}
		var arg1 *ledgerv1.ActionEvent
		if args[1] != nil {
			arg1 = args[1].(*ledgerv1.ActionEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSealer_Seal_Call) Return(actionEvent *ledgerv1.ActionEvent, err error) *MockSealer_Seal_Call {
	_c.Call.Return(actionEvent, err)
	return _c
}

func (_c *MockSealer_Seal_Call) RunAndReturn(run func(event *ledgerv1.ActionEvent, prev *ledgerv1.ActionEvent) (*ledgerv1.ActionEvent, error)) *MockSealer_Seal_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyLink provides a mock function for the type MockSealer
func (_mock *MockSealer) VerifyLink(event *ledgerv1.ActionEvent, prev *ledgerv1.ActionEvent) error {
	ret := _mock.Called(event, prev)

	if len(ret) == 0 {
		panic("no return value specified for VerifyLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*ledgerv1.ActionEvent, *ledgerv1.ActionEvent) error); ok {
		r0 = returnFunc(event, prev)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSealer_VerifyLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyLink'
type MockSealer_VerifyLink_Call struct {
	*mock.Call
}

// VerifyLink is a helper method to define mock.On call
//   - event *ledgerv1.ActionEvent
//   - prev *ledgerv1.ActionEvent
func (_e *MockSealer_Expecter) VerifyLink(event any, prev any) *MockSealer_VerifyLink_Call {
	return &MockSealer_VerifyLink_Call{Call: _e.mock.On("VerifyLink", event, prev)}
}

func (_c *MockSealer_VerifyLink_Call) Run(run func(event *ledgerv1.ActionEvent, prev *ledgerv1.ActionEvent)) *MockSealer_VerifyLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ledgerv1.ActionEvent
		if args[0] != nil {
			arg0 = args[0].(*ledgerv1.ActionEvent)
		}
		var arg1 *ledgerv1.ActionEvent
		if args[1] != nil {
			arg1 = args[1].(*ledgerv1.ActionEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSealer_VerifyLink_Call) Return(err error) *MockSealer_VerifyLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSealer_VerifyLink_Call) RunAndReturn(run func(event *ledgerv1.ActionEvent, prev *ledgerv1.ActionEvent) error) *MockSealer_VerifyLink_Call {
	_c.Call.Return(run)
	return _c
}
