// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/babit/nal/gen/solari/ledger/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionStore creates a new instance of MockSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStore {
	mock := &MockSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionStore is an autogenerated mock type for the SessionStore type
type MockSessionStore struct {
	mock.Mock
}

type MockSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStore) EXPECT() *MockSessionStore_Expecter {
	return &MockSessionStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSessionStore
func (_mock *MockSessionStore) Create(ctx context.Context, session *ledgerv1.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ledgerv1.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *ledgerv1.Session
func (_e *MockSessionStore_Expecter) Create(ctx any, session any) *MockSessionStore_Create_Call {
	return &MockSessionStore_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *MockSessionStore_Create_Call) Run(run func(ctx context.Context, session *ledgerv1.Session)) *MockSessionStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ledgerv1.Session
		if args[1] != nil {
			arg1 = args[1].(*ledgerv1.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionStore_Create_Call) Return(err error) *MockSessionStore_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionStore_Create_Call) RunAndReturn(run func(ctx context.Context, session *ledgerv1.Session) error) *MockSessionStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// End provides a mock function for the type MockSessionStore
func (_mock *MockSessionStore) End(ctx context.Context, sessionID string, at time.Time) (*ledgerv1.Session, error) {
	ret := _mock.Called(ctx, sessionID, at)

	if len(ret) == 0 {
		panic("no return value specified for End")
	}

	var r0 *ledgerv1.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (*ledgerv1.Session, error)); ok {
		return returnFunc(ctx, sessionID, at)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) *ledgerv1.Session); ok {
		r0 = returnFunc(ctx, sessionID, at)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ledgerv1.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, sessionID, at)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionStore_End_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'End'
type MockSessionStore_End_Call struct {
	*mock.Call
}

// End is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - at time.Time
func (_e *MockSessionStore_Expecter) End(ctx any, sessionID any, at any) *MockSessionStore_End_Call {
	return &MockSessionStore_End_Call{Call: _e.mock.On("End", ctx, sessionID, at)}
}

func (_c *MockSessionStore_End_Call) Run(run func(ctx context.Context, sessionID string, at time.Time)) *MockSessionStore_End_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionStore_End_Call) Return(session *ledgerv1.Session, err error) *MockSessionStore_End_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionStore_End_Call) RunAndReturn(run func(ctx context.Context, sessionID string, at time.Time) (*ledgerv1.Session, error)) *MockSessionStore_End_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockSessionStore
func (_mock *MockSessionStore) Get(ctx context.Context, sessionID string) (*ledgerv1.Session, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *ledgerv1.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ledgerv1.Session, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ledgerv1.Session); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ledgerv1.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockSessionStore_Expecter) Get(ctx any, sessionID any) *MockSessionStore_Get_Call {
	return &MockSessionStore_Get_Call{Call: _e.mock.On("Get", ctx, sessionID)}
}

func (_c *MockSessionStore_Get_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionStore_Get_Call) Return(session *ledgerv1.Session, err error) *MockSessionStore_Get_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionStore_Get_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*ledgerv1.Session, error)) *MockSessionStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NextSequence provides a mock function for the type MockSessionStore
func (_mock *MockSessionStore) NextSequence(ctx context.Context, sessionID string) (int64, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for NextSequence")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionStore_NextSequence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextSequence'
type MockSessionStore_NextSequence_Call struct {
	*mock.Call
}

// NextSequence is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockSessionStore_Expecter) NextSequence(ctx any, sessionID any) *MockSessionStore_NextSequence_Call {
	return &MockSessionStore_NextSequence_Call{Call: _e.mock.On("NextSequence", ctx, sessionID)}
}

func (_c *MockSessionStore_NextSequence_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionStore_NextSequence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionStore_NextSequence_Call) Return(n int64, err error) *MockSessionStore_NextSequence_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSessionStore_NextSequence_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (int64, error)) *MockSessionStore_NextSequence_Call {
	_c.Call.Return(run)
	return _c
}
