// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSigner creates a new instance of MockSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSigner {
	mock := &MockSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSigner is an autogenerated mock type for the Signer type
type MockSigner struct {
	mock.Mock
}

type MockSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSigner) EXPECT() *MockSigner_Expecter {
	return &MockSigner_Expecter{mock: &_m.Mock}
}

// PublicKey provides a mock function for the type MockSigner
func (_mock *MockSigner) PublicKey(keyID string) ([]byte, bool) {
	ret := _mock.Called(keyID)

	if len(ret) == 0 {
		panic("no return value specified for PublicKey")
	}

	var r0 []byte
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, bool)); ok {
		return returnFunc(keyID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(keyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(keyID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockSigner_PublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublicKey'
type MockSigner_PublicKey_Call struct {
	*mock.Call
}

// PublicKey is a helper method to define mock.On call
//   - keyID string
func (_e *MockSigner_Expecter) PublicKey(keyID any) *MockSigner_PublicKey_Call {
	return &MockSigner_PublicKey_Call{Call: _e.mock.On("PublicKey", keyID)}
}

func (_c *MockSigner_PublicKey_Call) Run(run func(keyID string)) *MockSigner_PublicKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSigner_PublicKey_Call) Return(bytes []byte, b bool) *MockSigner_PublicKey_Call {
	_c.Call.Return(bytes, b)
	return _c
}

func (_c *MockSigner_PublicKey_Call) RunAndReturn(run func(keyID string) ([]byte, bool)) *MockSigner_PublicKey_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function for the type MockSigner
func (_mock *MockSigner) Sign(msg []byte) ([]byte, string, error) {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 []byte
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, string, error)); ok {
		return returnFunc(msg)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) string); ok {
		r1 = returnFunc(msg)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func([]byte) error); ok {
		r2 = returnFunc(msg)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSigner_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockSigner_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - msg []byte
func (_e *MockSigner_Expecter) Sign(msg any) *MockSigner_Sign_Call {
	return &MockSigner_Sign_Call{Call: _e.mock.On("Sign", msg)}
}

func (_c *MockSigner_Sign_Call) Run(run func(msg []byte)) *MockSigner_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSigner_Sign_Call) Return(sig []byte, keyID string, err error) *MockSigner_Sign_Call {
	_c.Call.Return(sig, keyID, err)
	return _c
}

func (_c *MockSigner_Sign_Call) RunAndReturn(run func(msg []byte) ([]byte, string, error)) *MockSigner_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockSigner
func (_mock *MockSigner) Verify(msg []byte, sig []byte, keyID string) bool {
	ret := _mock.Called(msg, sig, keyID)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte, string) bool); ok {
		r0 = returnFunc(msg, sig, keyID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSigner_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockSigner_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - msg []byte
//   - sig []byte
//   - keyID string
func (_e *MockSigner_Expecter) Verify(msg any, sig any, keyID any) *MockSigner_Verify_Call {
	return &MockSigner_Verify_Call{Call: _e.mock.On("Verify", msg, sig, keyID)}
}

func (_c *MockSigner_Verify_Call) Run(run func(msg []byte, sig []byte, keyID string)) *MockSigner_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSigner_Verify_Call) Return(b bool) *MockSigner_Verify_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSigner_Verify_Call) RunAndReturn(run func(msg []byte, sig []byte, keyID string) bool) *MockSigner_Verify_Call {
	_c.Call.Return(run)
	return _c
}
