// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSolari creates a new instance of MockSolari. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSolari(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSolari {
	mock := &MockSolari{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSolari is an autogenerated mock type for the Solari type
type MockSolari struct {
	mock.Mock
}

type MockSolari_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSolari) EXPECT() *MockSolari_Expecter {
	return &MockSolari_Expecter{mock: &_m.Mock}
}

// Recording provides a mock function for the type MockSolari
func (_mock *MockSolari) Recording(ctx context.Context, ref string) ([]byte, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Recording")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSolari_Recording_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recording'
type MockSolari_Recording_Call struct {
	*mock.Call
}

// Recording is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
func (_e *MockSolari_Expecter) Recording(ctx any, ref any) *MockSolari_Recording_Call {
	return &MockSolari_Recording_Call{Call: _e.mock.On("Recording", ctx, ref)}
}

func (_c *MockSolari_Recording_Call) Run(run func(ctx context.Context, ref string)) *MockSolari_Recording_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSolari_Recording_Call) Return(bytes []byte, err error) *MockSolari_Recording_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockSolari_Recording_Call) RunAndReturn(run func(ctx context.Context, ref string) ([]byte, error)) *MockSolari_Recording_Call {
	_c.Call.Return(run)
	return _c
}
