// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/babit/nal/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserStore creates a new instance of MockUserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserStore {
	mock := &MockUserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserStore is an autogenerated mock type for the UserStore type
type MockUserStore struct {
	mock.Mock
}

type MockUserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserStore) EXPECT() *MockUserStore_Expecter {
	return &MockUserStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserStore
func (_mock *MockUserStore) Create(ctx context.Context, u *ports.User) (*ports.User, error) {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *ports.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ports.User) (*ports.User, error)); ok {
		return returnFunc(ctx, u)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ports.User) *ports.User); ok {
		r0 = returnFunc(ctx, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ports.User) error); ok {
		r1 = returnFunc(ctx, u)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - u *ports.User
func (_e *MockUserStore_Expecter) Create(ctx any, u any) *MockUserStore_Create_Call {
	return &MockUserStore_Create_Call{Call: _e.mock.On("Create", ctx, u)}
}

func (_c *MockUserStore_Create_Call) Run(run func(ctx context.Context, u *ports.User)) *MockUserStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ports.User
		if args[1] != nil {
			arg1 = args[1].(*ports.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserStore_Create_Call) Return(user *ports.User, err error) *MockUserStore_Create_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserStore_Create_Call) RunAndReturn(run func(ctx context.Context, u *ports.User) (*ports.User, error)) *MockUserStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockUserStore
func (_mock *MockUserStore) GetByEmail(ctx context.Context, email string) (*ports.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *ports.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ports.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ports.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStore_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserStore_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserStore_Expecter) GetByEmail(ctx any, email any) *MockUserStore_GetByEmail_Call {
	return &MockUserStore_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserStore_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserStore_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserStore_GetByEmail_Call) Return(user *ports.User, err error) *MockUserStore_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserStore_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*ports.User, error)) *MockUserStore_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockUserStore
func (_mock *MockUserStore) GetByID(ctx context.Context, id string) (*ports.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *ports.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ports.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ports.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserStore_Expecter) GetByID(ctx any, id any) *MockUserStore_GetByID_Call {
	return &MockUserStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserStore_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockUserStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserStore_GetByID_Call) Return(user *ports.User, err error) *MockUserStore_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserStore_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*ports.User, error)) *MockUserStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserStore
func (_mock *MockUserStore) Update(ctx context.Context, id string, orgName string, orgDomain string, industry string) (*ports.User, error) {
	ret := _mock.Called(ctx, id, orgName, orgDomain, industry)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *ports.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*ports.User, error)); ok {
		return returnFunc(ctx, id, orgName, orgDomain, industry)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *ports.User); ok {
		r0 = returnFunc(ctx, id, orgName, orgDomain, industry)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, id, orgName, orgDomain, industry)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - orgName string
//   - orgDomain string
//   - industry string
func (_e *MockUserStore_Expecter) Update(ctx any, id any, orgName any, orgDomain any, industry any) *MockUserStore_Update_Call {
	return &MockUserStore_Update_Call{Call: _e.mock.On("Update", ctx, id, orgName, orgDomain, industry)}
}

func (_c *MockUserStore_Update_Call) Run(run func(ctx context.Context, id string, orgName string, orgDomain string, industry string)) *MockUserStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUserStore_Update_Call) Return(user *ports.User, err error) *MockUserStore_Update_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserStore_Update_Call) RunAndReturn(run func(ctx context.Context, id string, orgName string, orgDomain string, industry string) (*ports.User, error)) *MockUserStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
