// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEvents = `-- name: CountEvents :one
SELECT count(*) FROM events
`

func (q *Queries) CountEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGrants = `-- name: CountGrants :one
SELECT count(*) FROM grants
`

func (q *Queries) CountGrants(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGrants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRevocations = `-- name: CountRevocations :one
SELECT count(*) FROM revocations
`

func (q *Queries) CountRevocations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRevocations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSessions = `-- name: CountSessions :one
SELECT count(*) FROM sessions
`

func (q *Queries) CountSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const eventsByDay = `-- name: EventsByDay :many
SELECT date_trunc('day', occurred_at)::timestamptz AS day, count(*) AS n
FROM events
WHERE occurred_at >= now() - make_interval(days => $1::int)
GROUP BY day
ORDER BY day
`

type EventsByDayRow struct {
	Day pgtype.Timestamptz
	N   int64
}

func (q *Queries) EventsByDay(ctx context.Context, dollar_1 int32) ([]EventsByDayRow, error) {
	rows, err := q.db.Query(ctx, eventsByDay, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsByDayRow{}
	for rows.Next() {
		var i EventsByDayRow
		if err := rows.Scan(&i.Day, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsBySurface = `-- name: EventsBySurface :many
SELECT surface, count(*) AS n FROM events GROUP BY surface ORDER BY surface
`

type EventsBySurfaceRow struct {
	Surface int32
	N       int64
}

func (q *Queries) EventsBySurface(ctx context.Context) ([]EventsBySurfaceRow, error) {
	rows, err := q.db.Query(ctx, eventsBySurface)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsBySurfaceRow{}
	for rows.Next() {
		var i EventsBySurfaceRow
		if err := rows.Scan(&i.Surface, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
