// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEventsByUser = `-- name: CountEventsByUser :one
SELECT count(*)
FROM events e
JOIN sessions s ON e.session_id = s.session_id
WHERE s.user_id = $1
`

func (q *Queries) CountEventsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGrantsByUser = `-- name: CountGrantsByUser :one
SELECT count(*) FROM grants WHERE user_id = $1
`

func (q *Queries) CountGrantsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGrantsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRevocationsByUser = `-- name: CountRevocationsByUser :one
SELECT count(*)
FROM revocations r
JOIN grants g ON r.grant_id = g.grant_id
WHERE g.user_id = $1
`

func (q *Queries) CountRevocationsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRevocationsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSessionsByUser = `-- name: CountSessionsByUser :one
SELECT count(*) FROM sessions WHERE user_id = $1
`

func (q *Queries) CountSessionsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const eventsByDayForUser = `-- name: EventsByDayForUser :many
SELECT date_trunc('day', e.occurred_at)::timestamptz AS day, count(*) AS n
FROM events e
JOIN sessions s ON e.session_id = s.session_id
WHERE s.user_id = $1
  AND e.occurred_at >= now() - make_interval(days => $2::int)
GROUP BY day
ORDER BY day
`

type EventsByDayForUserParams struct {
	UserID  pgtype.UUID
	Column2 int32
}

type EventsByDayForUserRow struct {
	Day pgtype.Timestamptz
	N   int64
}

func (q *Queries) EventsByDayForUser(ctx context.Context, arg EventsByDayForUserParams) ([]EventsByDayForUserRow, error) {
	rows, err := q.db.Query(ctx, eventsByDayForUser, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsByDayForUserRow{}
	for rows.Next() {
		var i EventsByDayForUserRow
		if err := rows.Scan(&i.Day, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsBySurfaceForUser = `-- name: EventsBySurfaceForUser :many
SELECT e.surface, count(*) AS n
FROM events e
JOIN sessions s ON e.session_id = s.session_id
WHERE s.user_id = $1
GROUP BY e.surface
ORDER BY e.surface
`

type EventsBySurfaceForUserRow struct {
	Surface int32
	N       int64
}

func (q *Queries) EventsBySurfaceForUser(ctx context.Context, userID pgtype.UUID) ([]EventsBySurfaceForUserRow, error) {
	rows, err := q.db.Query(ctx, eventsBySurfaceForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsBySurfaceForUserRow{}
	for rows.Next() {
		var i EventsBySurfaceForUserRow
		if err := rows.Scan(&i.Surface, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topRecordingRefsForUser = `-- name: TopRecordingRefsForUser :many
SELECT e.recording_ref AS url, count(*) AS n
FROM events e
JOIN sessions s ON e.session_id = s.session_id
WHERE s.user_id = $1
  AND e.recording_ref <> ''
  AND e.occurred_at >= now() - make_interval(days => $2::int)
GROUP BY e.recording_ref
ORDER BY n DESC
LIMIT $3
`

type TopRecordingRefsForUserParams struct {
	UserID  pgtype.UUID
	Column2 int32
	Limit   int32
}

type TopRecordingRefsForUserRow struct {
	Url string
	N   int64
}

func (q *Queries) TopRecordingRefsForUser(ctx context.Context, arg TopRecordingRefsForUserParams) ([]TopRecordingRefsForUserRow, error) {
	rows, err := q.db.Query(ctx, topRecordingRefsForUser, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopRecordingRefsForUserRow{}
	for rows.Next() {
		var i TopRecordingRefsForUserRow
		if err := rows.Scan(&i.Url, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
