// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anchors.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAnchor = `-- name: GetAnchor :one
SELECT session_id, kind, root, anchor_receipt, anchored_at FROM anchors WHERE session_id = $1
`

func (q *Queries) GetAnchor(ctx context.Context, sessionID string) (Anchor, error) {
	row := q.db.QueryRow(ctx, getAnchor, sessionID)
	var i Anchor
	err := row.Scan(
		&i.SessionID,
		&i.Kind,
		&i.Root,
		&i.AnchorReceipt,
		&i.AnchoredAt,
	)
	return i, err
}

const upsertAnchor = `-- name: UpsertAnchor :exec
INSERT INTO anchors (session_id, kind, root, anchor_receipt, anchored_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (session_id) DO UPDATE SET
    kind = EXCLUDED.kind,
    root = EXCLUDED.root,
    anchor_receipt = EXCLUDED.anchor_receipt,
    anchored_at = EXCLUDED.anchored_at
`

type UpsertAnchorParams struct {
	SessionID     string
	Kind          string
	Root          []byte
	AnchorReceipt []byte
	AnchoredAt    pgtype.Timestamptz
}

func (q *Queries) UpsertAnchor(ctx context.Context, arg UpsertAnchorParams) error {
	_, err := q.db.Exec(ctx, upsertAnchor,
		arg.SessionID,
		arg.Kind,
		arg.Root,
		arg.AnchorReceipt,
		arg.AnchoredAt,
	)
	return err
}
