// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendEvent = `-- name: AppendEvent :exec
INSERT INTO events (
    event_id, project_id, session_id, sequence, surface, action_type, action_payload,
    grant_id, pre_state_hash, post_state_hash, recording_ref, occurred_at,
    content_hash, prev_hash, notary_signature
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
`

type AppendEventParams struct {
	EventID         string
	ProjectID       pgtype.UUID
	SessionID       string
	Sequence        int64
	Surface         int32
	ActionType      string
	ActionPayload   []byte
	GrantID         string
	PreStateHash    []byte
	PostStateHash   []byte
	RecordingRef    string
	OccurredAt      pgtype.Timestamptz
	ContentHash     []byte
	PrevHash        []byte
	NotarySignature []byte
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.db.Exec(ctx, appendEvent,
		arg.EventID,
		arg.ProjectID,
		arg.SessionID,
		arg.Sequence,
		arg.Surface,
		arg.ActionType,
		arg.ActionPayload,
		arg.GrantID,
		arg.PreStateHash,
		arg.PostStateHash,
		arg.RecordingRef,
		arg.OccurredAt,
		arg.ContentHash,
		arg.PrevHash,
		arg.NotarySignature,
	)
	return err
}

const eventsBySession = `-- name: EventsBySession :many
SELECT event_id, session_id, sequence, surface, action_type, action_payload, grant_id, pre_state_hash, post_state_hash, recording_ref, occurred_at, content_hash, prev_hash, notary_signature, uuid, project_id FROM events
WHERE session_id = $1
ORDER BY sequence
`

func (q *Queries) EventsBySession(ctx context.Context, sessionID string) ([]Event, error) {
	rows, err := q.db.Query(ctx, eventsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.SessionID,
			&i.Sequence,
			&i.Surface,
			&i.ActionType,
			&i.ActionPayload,
			&i.GrantID,
			&i.PreStateHash,
			&i.PostStateHash,
			&i.RecordingRef,
			&i.OccurredAt,
			&i.ContentHash,
			&i.PrevHash,
			&i.NotarySignature,
			&i.Uuid,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsInRange = `-- name: EventsInRange :many
SELECT event_id, session_id, sequence, surface, action_type, action_payload, grant_id, pre_state_hash, post_state_hash, recording_ref, occurred_at, content_hash, prev_hash, notary_signature, uuid, project_id FROM events
WHERE sequence >= $1 AND sequence <= $2
ORDER BY sequence
`

type EventsInRangeParams struct {
	Sequence   int64
	Sequence_2 int64
}

func (q *Queries) EventsInRange(ctx context.Context, arg EventsInRangeParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, eventsInRange, arg.Sequence, arg.Sequence_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.SessionID,
			&i.Sequence,
			&i.Surface,
			&i.ActionType,
			&i.ActionPayload,
			&i.GrantID,
			&i.PreStateHash,
			&i.PostStateHash,
			&i.RecordingRef,
			&i.OccurredAt,
			&i.ContentHash,
			&i.PrevHash,
			&i.NotarySignature,
			&i.Uuid,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvent = `-- name: GetEvent :one
SELECT event_id, session_id, sequence, surface, action_type, action_payload, grant_id, pre_state_hash, post_state_hash, recording_ref, occurred_at, content_hash, prev_hash, notary_signature, uuid, project_id FROM events WHERE event_id = $1
`

func (q *Queries) GetEvent(ctx context.Context, eventID string) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, eventID)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.SessionID,
		&i.Sequence,
		&i.Surface,
		&i.ActionType,
		&i.ActionPayload,
		&i.GrantID,
		&i.PreStateHash,
		&i.PostStateHash,
		&i.RecordingRef,
		&i.OccurredAt,
		&i.ContentHash,
		&i.PrevHash,
		&i.NotarySignature,
		&i.Uuid,
		&i.ProjectID,
	)
	return i, err
}

const lastEventBySession = `-- name: LastEventBySession :one
SELECT event_id, session_id, sequence, surface, action_type, action_payload, grant_id, pre_state_hash, post_state_hash, recording_ref, occurred_at, content_hash, prev_hash, notary_signature, uuid, project_id FROM events
WHERE session_id = $1
ORDER BY sequence DESC
LIMIT 1
`

func (q *Queries) LastEventBySession(ctx context.Context, sessionID string) (Event, error) {
	row := q.db.QueryRow(ctx, lastEventBySession, sessionID)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.SessionID,
		&i.Sequence,
		&i.Surface,
		&i.ActionType,
		&i.ActionPayload,
		&i.GrantID,
		&i.PreStateHash,
		&i.PostStateHash,
		&i.RecordingRef,
		&i.OccurredAt,
		&i.ContentHash,
		&i.PrevHash,
		&i.NotarySignature,
		&i.Uuid,
		&i.ProjectID,
	)
	return i, err
}

const listEventsByUser = `-- name: ListEventsByUser :many
SELECT e.event_id, e.session_id, e.sequence, e.surface, e.action_type, e.action_payload, e.grant_id, e.pre_state_hash, e.post_state_hash, e.recording_ref, e.occurred_at, e.content_hash, e.prev_hash, e.notary_signature, e.uuid, e.project_id FROM events e
JOIN sessions s ON e.session_id = s.session_id
WHERE s.user_id = $1
  AND ($2::text = '' OR e.event_id < $2::text)
  AND ($4::text = '' OR e.project_id::text = $4)
ORDER BY e.event_id DESC
LIMIT $3
`

type ListEventsByUserParams struct {
	UserID  pgtype.UUID
	Column2 string
	Limit   int32
	Column4 string
}

func (q *Queries) ListEventsByUser(ctx context.Context, arg ListEventsByUserParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByUser,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.EventID,
			&i.SessionID,
			&i.Sequence,
			&i.Surface,
			&i.ActionType,
			&i.ActionPayload,
			&i.GrantID,
			&i.PreStateHash,
			&i.PostStateHash,
			&i.RecordingRef,
			&i.OccurredAt,
			&i.ContentHash,
			&i.PrevHash,
			&i.NotarySignature,
			&i.Uuid,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
