// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grants.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGrant = `-- name: GetGrant :one
SELECT grant_id, parent_grant_id, principal_id, subject_id, capabilities, resource_globs, max_value_cents, max_depth, expires_at, parent_signature, uuid, user_id FROM grants WHERE grant_id = $1
`

func (q *Queries) GetGrant(ctx context.Context, grantID string) (Grant, error) {
	row := q.db.QueryRow(ctx, getGrant, grantID)
	var i Grant
	err := row.Scan(
		&i.GrantID,
		&i.ParentGrantID,
		&i.PrincipalID,
		&i.SubjectID,
		&i.Capabilities,
		&i.ResourceGlobs,
		&i.MaxValueCents,
		&i.MaxDepth,
		&i.ExpiresAt,
		&i.ParentSignature,
		&i.Uuid,
		&i.UserID,
	)
	return i, err
}

const grantChain = `-- name: GrantChain :many
WITH RECURSIVE chain AS (
    SELECT g.grant_id, g.parent_grant_id, g.principal_id, g.subject_id, g.capabilities, g.resource_globs, g.max_value_cents, g.max_depth, g.expires_at, g.parent_signature, g.uuid, g.user_id, 0 AS depth
    FROM grants g
    WHERE g.grant_id = $1
    UNION ALL
    SELECT p.grant_id, p.parent_grant_id, p.principal_id, p.subject_id, p.capabilities, p.resource_globs, p.max_value_cents, p.max_depth, p.expires_at, p.parent_signature, p.uuid, p.user_id, c.depth + 1
    FROM grants p
    JOIN chain c ON p.grant_id = c.parent_grant_id
    WHERE c.parent_grant_id <> ''
)
SELECT grant_id, parent_grant_id, principal_id, subject_id, capabilities,
       resource_globs, max_value_cents, max_depth, expires_at, parent_signature
FROM chain
ORDER BY depth DESC
`

type GrantChainRow struct {
	GrantID         string
	ParentGrantID   string
	PrincipalID     string
	SubjectID       string
	Capabilities    []string
	ResourceGlobs   []string
	MaxValueCents   int64
	MaxDepth        int32
	ExpiresAt       pgtype.Timestamptz
	ParentSignature []byte
}

func (q *Queries) GrantChain(ctx context.Context, grantID string) ([]GrantChainRow, error) {
	rows, err := q.db.Query(ctx, grantChain, grantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GrantChainRow{}
	for rows.Next() {
		var i GrantChainRow
		if err := rows.Scan(
			&i.GrantID,
			&i.ParentGrantID,
			&i.PrincipalID,
			&i.SubjectID,
			&i.Capabilities,
			&i.ResourceGlobs,
			&i.MaxValueCents,
			&i.MaxDepth,
			&i.ExpiresAt,
			&i.ParentSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isRevoked = `-- name: IsRevoked :one
SELECT EXISTS (SELECT 1 FROM revocations WHERE grant_id = $1)
`

func (q *Queries) IsRevoked(ctx context.Context, grantID string) (bool, error) {
	row := q.db.QueryRow(ctx, isRevoked, grantID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const putGrant = `-- name: PutGrant :exec
INSERT INTO grants (
    grant_id, parent_grant_id, principal_id, subject_id, capabilities,
    resource_globs, max_value_cents, max_depth, expires_at, parent_signature, user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (grant_id) DO UPDATE SET
    parent_grant_id = EXCLUDED.parent_grant_id,
    principal_id = EXCLUDED.principal_id,
    subject_id = EXCLUDED.subject_id,
    capabilities = EXCLUDED.capabilities,
    resource_globs = EXCLUDED.resource_globs,
    max_value_cents = EXCLUDED.max_value_cents,
    max_depth = EXCLUDED.max_depth,
    expires_at = EXCLUDED.expires_at,
    parent_signature = EXCLUDED.parent_signature,
    user_id = COALESCE(grants.user_id, EXCLUDED.user_id)
`

type PutGrantParams struct {
	GrantID         string
	ParentGrantID   string
	PrincipalID     string
	SubjectID       string
	Capabilities    []string
	ResourceGlobs   []string
	MaxValueCents   int64
	MaxDepth        int32
	ExpiresAt       pgtype.Timestamptz
	ParentSignature []byte
	UserID          pgtype.UUID
}

func (q *Queries) PutGrant(ctx context.Context, arg PutGrantParams) error {
	_, err := q.db.Exec(ctx, putGrant,
		arg.GrantID,
		arg.ParentGrantID,
		arg.PrincipalID,
		arg.SubjectID,
		arg.Capabilities,
		arg.ResourceGlobs,
		arg.MaxValueCents,
		arg.MaxDepth,
		arg.ExpiresAt,
		arg.ParentSignature,
		arg.UserID,
	)
	return err
}

const revoke = `-- name: Revoke :exec
INSERT INTO revocations (grant_id, reason)
VALUES ($1, $2)
ON CONFLICT (grant_id) DO UPDATE SET reason = EXCLUDED.reason
`

type RevokeParams struct {
	GrantID string
	Reason  string
}

func (q *Queries) Revoke(ctx context.Context, arg RevokeParams) error {
	_, err := q.db.Exec(ctx, revoke, arg.GrantID, arg.Reason)
	return err
}
