// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	EventID         string
	SessionID       string
	Sequence        int64
	Surface         int32
	ActionType      string
	ActionPayload   []byte
	GrantID         string
	PreStateHash    []byte
	PostStateHash   []byte
	RecordingRef    string
	OccurredAt      pgtype.Timestamptz
	ContentHash     []byte
	PrevHash        []byte
	NotarySignature []byte
	Uuid            pgtype.UUID
}

type Grant struct {
	GrantID         string
	ParentGrantID   string
	PrincipalID     string
	SubjectID       string
	Capabilities    []string
	ResourceGlobs   []string
	MaxValueCents   int64
	MaxDepth        int32
	ExpiresAt       pgtype.Timestamptz
	ParentSignature []byte
	Uuid            pgtype.UUID
}

type Revocation struct {
	GrantID   string
	Reason    string
	RevokedAt pgtype.Timestamptz
}

type Session struct {
	SessionID   string
	RootGrantID string
	Surface     int32
	StartedAt   pgtype.Timestamptz
	EndedAt     pgtype.Timestamptz
	EventCount  int64
	Uuid        pgtype.UUID
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	AccountType  int32
	OrgName      string
	OrgDomain    string
	Industry     string
	BrandCompany string
	BrandLogoUrl string
	BrandColor   string
	CreatedAt    pgtype.Timestamptz
}
