// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (project_id, user_id, name, prefix, last4, key_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, user_id, name, prefix, last4, key_hash, created_at, revoked_at
`

type CreateApiKeyParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Prefix    string
	Last4     string
	KeyHash   string
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.ProjectID,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.Last4,
		arg.KeyHash,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Last4,
		&i.KeyHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, created_at
`

type CreateProjectParams struct {
	UserID pgtype.UUID
	Name   string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.UserID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, project_id, user_id, name, prefix, last4, key_hash, created_at, revoked_at FROM api_keys WHERE key_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Last4,
		&i.KeyHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getProjectForUser = `-- name: GetProjectForUser :one
SELECT id, user_id, name, created_at FROM projects WHERE id = $1 AND user_id = $2
`

type GetProjectForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetProjectForUser(ctx context.Context, arg GetProjectForUserParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForUser, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listApiKeysByProject = `-- name: ListApiKeysByProject :many
SELECT id, project_id, user_id, name, prefix, last4, key_hash, created_at, revoked_at FROM api_keys
WHERE project_id = $1
  AND ($2::text = '' OR id::text < $2)
ORDER BY id DESC
LIMIT $3
`

type ListApiKeysByProjectParams struct {
	ProjectID pgtype.UUID
	Column2   string
	Limit     int32
}

func (q *Queries) ListApiKeysByProject(ctx context.Context, arg ListApiKeysByProjectParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeysByProject, arg.ProjectID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.Last4,
			&i.KeyHash,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT
    p.id,
    p.user_id,
    p.name,
    p.created_at,
    (SELECT count(*) FROM api_keys k WHERE k.project_id = p.id AND k.revoked_at IS NULL) AS active_keys
FROM projects p
WHERE p.user_id = $1
  AND ($2::text = '' OR p.id::text < $2)
ORDER BY p.id DESC
LIMIT $3
`

type ListProjectsByUserParams struct {
	UserID  pgtype.UUID
	Column2 string
	Limit   int32
}

type ListProjectsByUserRow struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Name       string
	CreatedAt  pgtype.Timestamptz
	ActiveKeys int64
}

func (q *Queries) ListProjectsByUser(ctx context.Context, arg ListProjectsByUserParams) ([]ListProjectsByUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectsByUser, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsByUserRow{}
	for rows.Next() {
		var i ListProjectsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.ActiveKeys,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiKey = `-- name: RevokeApiKey :one
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
RETURNING id, project_id, user_id, name, prefix, last4, key_hash, created_at, revoked_at
`

type RevokeApiKeyParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeApiKey, arg.ID, arg.UserID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Last4,
		&i.KeyHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
