// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    session_id, project_id, root_grant_id, surface, started_at, ended_at, event_count, user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateSessionParams struct {
	SessionID   string
	ProjectID   pgtype.UUID
	RootGrantID string
	Surface     int32
	StartedAt   pgtype.Timestamptz
	EndedAt     pgtype.Timestamptz
	EventCount  int64
	UserID      pgtype.UUID
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.SessionID,
		arg.ProjectID,
		arg.RootGrantID,
		arg.Surface,
		arg.StartedAt,
		arg.EndedAt,
		arg.EventCount,
		arg.UserID,
	)
	return err
}

const endSession = `-- name: EndSession :one
UPDATE sessions
SET ended_at = $2
WHERE session_id = $1
RETURNING session_id, root_grant_id, surface, started_at, ended_at, event_count, uuid, user_id, project_id
`

type EndSessionParams struct {
	SessionID string
	EndedAt   pgtype.Timestamptz
}

func (q *Queries) EndSession(ctx context.Context, arg EndSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, endSession, arg.SessionID, arg.EndedAt)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.RootGrantID,
		&i.Surface,
		&i.StartedAt,
		&i.EndedAt,
		&i.EventCount,
		&i.Uuid,
		&i.UserID,
		&i.ProjectID,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT session_id, root_grant_id, surface, started_at, ended_at, event_count, uuid, user_id, project_id FROM sessions WHERE session_id = $1
`

func (q *Queries) GetSession(ctx context.Context, sessionID string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, sessionID)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.RootGrantID,
		&i.Surface,
		&i.StartedAt,
		&i.EndedAt,
		&i.EventCount,
		&i.Uuid,
		&i.UserID,
		&i.ProjectID,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT session_id, root_grant_id, surface, started_at, ended_at, event_count, uuid, user_id, project_id FROM sessions
WHERE user_id = $1
  AND ($2::text = '' OR session_id < $2::text)
  AND ($4::text = '' OR project_id::text = $4)
ORDER BY session_id DESC
LIMIT $3
`

type ListSessionsByUserParams struct {
	UserID  pgtype.UUID
	Column2 string
	Limit   int32
	Column4 string
}

func (q *Queries) ListSessionsByUser(ctx context.Context, arg ListSessionsByUserParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.SessionID,
			&i.RootGrantID,
			&i.Surface,
			&i.StartedAt,
			&i.EndedAt,
			&i.EventCount,
			&i.Uuid,
			&i.UserID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSequence = `-- name: NextSequence :one
UPDATE sessions
SET event_count = event_count + 1
WHERE session_id = $1
RETURNING event_count
`

func (q *Queries) NextSequence(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRow(ctx, nextSequence, sessionID)
	var event_count int64
	err := row.Scan(&event_count)
	return event_count, err
}
