// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    session_id, root_grant_id, surface, started_at, ended_at, event_count
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateSessionParams struct {
	SessionID   string
	RootGrantID string
	Surface     int32
	StartedAt   pgtype.Timestamptz
	EndedAt     pgtype.Timestamptz
	EventCount  int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.SessionID,
		arg.RootGrantID,
		arg.Surface,
		arg.StartedAt,
		arg.EndedAt,
		arg.EventCount,
	)
	return err
}

const endSession = `-- name: EndSession :one
UPDATE sessions
SET ended_at = $2
WHERE session_id = $1
RETURNING session_id, root_grant_id, surface, started_at, ended_at, event_count
`

type EndSessionParams struct {
	SessionID string
	EndedAt   pgtype.Timestamptz
}

func (q *Queries) EndSession(ctx context.Context, arg EndSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, endSession, arg.SessionID, arg.EndedAt)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.RootGrantID,
		&i.Surface,
		&i.StartedAt,
		&i.EndedAt,
		&i.EventCount,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT session_id, root_grant_id, surface, started_at, ended_at, event_count FROM sessions WHERE session_id = $1
`

func (q *Queries) GetSession(ctx context.Context, sessionID string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, sessionID)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.RootGrantID,
		&i.Surface,
		&i.StartedAt,
		&i.EndedAt,
		&i.EventCount,
	)
	return i, err
}

const nextSequence = `-- name: NextSequence :one
UPDATE sessions
SET event_count = event_count + 1
WHERE session_id = $1
RETURNING event_count
`

func (q *Queries) NextSequence(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRow(ctx, nextSequence, sessionID)
	var event_count int64
	err := row.Scan(&event_count)
	return event_count, err
}
