// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, password_hash, account_type, org_name, org_domain, industry,
    brand_company, brand_logo_url, brand_color
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, email, password_hash, account_type, org_name, org_domain, industry, brand_company, brand_logo_url, brand_color, created_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	AccountType  int32
	OrgName      string
	OrgDomain    string
	Industry     string
	BrandCompany string
	BrandLogoUrl string
	BrandColor   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.AccountType,
		arg.OrgName,
		arg.OrgDomain,
		arg.Industry,
		arg.BrandCompany,
		arg.BrandLogoUrl,
		arg.BrandColor,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AccountType,
		&i.OrgName,
		&i.OrgDomain,
		&i.Industry,
		&i.BrandCompany,
		&i.BrandLogoUrl,
		&i.BrandColor,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, account_type, org_name, org_domain, industry, brand_company, brand_logo_url, brand_color, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AccountType,
		&i.OrgName,
		&i.OrgDomain,
		&i.Industry,
		&i.BrandCompany,
		&i.BrandLogoUrl,
		&i.BrandColor,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, account_type, org_name, org_domain, industry, brand_company, brand_logo_url, brand_color, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AccountType,
		&i.OrgName,
		&i.OrgDomain,
		&i.Industry,
		&i.BrandCompany,
		&i.BrandLogoUrl,
		&i.BrandColor,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET org_name = $2, org_domain = $3, industry = $4
WHERE id = $1
RETURNING id, email, password_hash, account_type, org_name, org_domain, industry, brand_company, brand_logo_url, brand_color, created_at
`

type UpdateUserParams struct {
	ID        pgtype.UUID
	OrgName   string
	OrgDomain string
	Industry  string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.OrgName,
		arg.OrgDomain,
		arg.Industry,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AccountType,
		&i.OrgName,
		&i.OrgDomain,
		&i.Industry,
		&i.BrandCompany,
		&i.BrandLogoUrl,
		&i.BrandColor,
		&i.CreatedAt,
	)
	return i, err
}
